// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

type ListPetsResponse struct {

	// pets
	Pets []*Pet `json:"pets"`

	// total items
	TotalItems int64 `json:"totalItems,omitempty"`
}
